theme = "gruvbox-dark"
icons = "awesome"

[[block]]
block = "cpu"
interval = 2
format = "{utilization}"

[[block]]
block = "net"
device = "wlp1s0"
format = "{ssid}"
interval = 5

[[block]]
block = "sound"
format = "{volume}"

[[block]]
block = "battery"
interval = 10
format = "{percentage}"

[[block]]
block = "time"
interval = 60
format = "%a %Y/%m/%d %I:%M %p | %j/365"
