theme = "gruvbox-dark"
icons = "awesome"

[[block]]
block = "cpu"
interval = 2
format = "{utilization}%"

[[block]]
block = "net"
device = "wlan0"
format = "{ssid} {speed_down}"
interval = 5
use_bits = false

[[block]]
block = "battery"
interval = 10
format = "{percentage}% {time}"

[[block]]
block = "time"
interval = 60
format = "%a %d/%m %R"
